### ISSUE TITLE
求问大佬何时更新源码，对这个项目很感兴趣

### ISSUE THREAD

**Issue by yc0815024** [hecongqing/CCKS2019_EventEntityExtraction_Rank5#1]
求问大佬何时更新源码，对这个项目很感兴趣

**Comment by hecongqing** [comment]
我周末来更新一下代码
________________________________
发件人: yc0815024 <notifications@github.com>
发送时间: 2019年11月8日 3:40
收件人: hecongqing/CCKS2019EventEntityExtraction_Rank5 <CCKS2019EventEntityExtraction_Rank5@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [hecongqing/CCKS2019EventEntityExtraction_Rank5] 求问大佬何时更新源码，对这个项目很感兴趣 (#1)


求问大佬何时更新源码，对这个项目很感兴趣

―

**Comment by yc0815024** [comment]
期待中，谢谢您

**Comment by hecongqing** [comment]
> 期待中，谢谢您
